version: '3.7'

services:

  nginx:
    image: nginx:1.17.9
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - url-shortener

  url-shortener:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    deploy:
      replicas: 5
      restart_policy:
        max_attempts: 3
        condition: on-failure       
      update_config:
        parallelism: 3
        delay: 10s
    expose:
      - 5000
    ports:
      - 5000
    networks:
      - default
    depends_on:
      - "redis"
    command: npm start
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PREFIX_URL: ${PREFIX_URL}
      EXPIRATION_HOUR: ${EXPIRATION_HOUR}
      ENV: production
      
  redis:
    image: redis:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - default
    ports:
      - 6379
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local

networks:
  default:
    driver: bridge